# Numpy Introduction

One of the most widely used libraries for machine learning and deep learning is `numpy`. This library is useful for any kind of computation which involves multi-arrays, matrices, and linear algebra. Visit [this link](https://numpy.org/) to explore the library

In this notebook, you will learn the basics of the numpy library

Have fun :)

In [1]:
import numpy as np # It's very common to abbreviate numpy as np.

1. [Defining An Array](#Defining-An-Array)
    1. [np.array](#np.array)
    2. [Important Properties Of An Array](#Important-Properties-Of-An-Array)
    2. [np.zeros, np.ones, np.eye](#np.zeros,-np.ones,-np.eye)
    3. [Random Arrays](#Random-Arrays)
2. [Basic Operations](#Basic-Operations)
    1. [Basic Math](#Basic-Math)
    2. [numpy broadcasting](#numpy-broadcasting)
    3. [Slicing](#Slicing)
    4. [Useful Methods](#Useful-Methods)

# Defining An Array

Basically, numpy is just a library to manipulate multi-dimensional arrays (Tensors).

## np.array

There are many ways to define a multi-dimensional array. The very first way is to use `np.array` method.

In [2]:
array = np.array([1, 2, 3])
array

array([1, 2, 3])

## Important Properties Of An Array

Every array in numpy has a shape that as the name suggests, defines the shape of the array. For example, the `array` that is defined in the previous cell has the shape `(3,)`. Note that the shape of an array is a python **tuple**. For this specific array, because it has just one dimension, the shape tuple has just one element. As you might guess, the shape of a matrix has two numbers, the shape of a three-dimensional array has three items, and so on.

To get the shape of an array, use the `shape` property.

### shape

In [3]:
array.shape

(3,)

### ndim

The second important property of an array is `ndim` which defines the dimensionality of the array (number of elements in the `shape` tuple).



In [4]:
array.ndim

1

### dtype

The last important property of an array is its dtype which specifies the type of data that is stored in the array.

Commonly used dtypes are `np.int32`, `np.int64`, `np.float32`, and, `np.float64`

To get the dtype of an array, use the `dtype` property.

In [5]:
array.dtype

dtype('int32')

You can use `astype` method to convert the dtype of an array.

In [6]:
array.astype(np.float32)

array([1., 2., 3.], dtype=float32)

### More Examples

In [7]:
scaler = np.array([1.])

print(f'array:\n{scaler}\n')
print(f'shape: {scaler.shape}')
print(f'ndim: {scaler.ndim}')
print(f'dtype: {scaler.dtype}')

array:
[1.]

shape: (1,)
ndim: 1
dtype: float64


In [8]:
matrix = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])

print(f'array:\n{matrix}\n')
print(f'shape: {matrix.shape}')
print(f'ndim: {matrix.ndim}')
print(f'dtype: {matrix.dtype}')

array:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

shape: (3, 3)
ndim: 2
dtype: float64


In [9]:
tensor = np.array([[[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]], [[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]]])

print(f'array:\n{tensor}\n')
print(f'shape: {tensor.shape}')
print(f'ndim: {tensor.ndim}')
print(f'dtype: {tensor.dtype}')

array:
[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]

 [[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]

shape: (2, 3, 3)
ndim: 3
dtype: float64


## np.zeros, np.ones, np.eye

In [10]:
ones = np.ones((2, 2)) # You can use this method to generate an array in which all of its elements are ones.
ones

array([[1., 1.],
       [1., 1.]])

In [11]:
zeros = np.zeros((2, 2)) # You can use this method to generate an array in which all of its elements are zeros.
zeros

array([[0., 0.],
       [0., 0.]])

In [12]:
eye3 = np.eye(3) ## You can use this method to generate the eigen matrix.
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random Arrays

To generate an array of randomly-generated numbers, you can use np.random module.

There are many useful methods in this module namely, `randn`, `randint`, `rand`, `uniform`, `normal`, and many others.

In [13]:
randn = np.random.randn(3, 3)
randn

array([[-0.09167875,  0.28520619,  1.10548469],
       [ 1.19640742,  0.7862293 ,  0.77085358],
       [-0.49994065, -0.08393755,  1.18245136]])

In [14]:
rand = np.random.rand(3, 3)
rand

array([[0.06997187, 0.04936635, 0.01626401],
       [0.86421913, 0.96966974, 0.30459124],
       [0.95136342, 0.37939154, 0.59799753]])

In [15]:
randint = np.random.randint(size=(3, 3), low=0, high=4)
randint

array([[0, 0, 3],
       [0, 3, 1],
       [0, 3, 3]])

In [16]:
uniform = np.random.uniform(size=(3, 3), low=0, high=4)
uniform

array([[2.90621064, 3.68771308, 1.67611533],
       [0.69316079, 3.71231351, 1.45137042],
       [3.32609486, 3.19082195, 0.20290915]])

In [17]:
normal = np.random.normal(size=(3, 3), loc=0, scale=1)
normal

array([[-2.25516333,  0.97445013, -1.23756827],
       [ 0.28798271, -1.00040311, -0.37013928],
       [-1.97394138, -0.35766896,  0.07315423]])

# Basic Operations

In [18]:
first  = np.array([1, 2, 3])
second = np.array([4, 5, 6])

## Basic Math

In [19]:
# to sum arrays you can use the add method
add = np.add(first, second) # you can also to the same computation with first + second
add

array([5, 7, 9])

In [20]:
# to subtract arrays you can use the subtract method
subtract = np.subtract(first, second) # you can also to the same computation with first - second
subtract

array([-3, -3, -3])

In [21]:
# To apply the element-wise product you can use the code below:
product = first * second
product

array([ 4, 10, 18])

In [22]:
# To apply the element-wise division you can use the code below:
division  = first / second
division 

array([0.25, 0.4 , 0.5 ])

In [23]:
# You can use .dot method to apply the dot product
dot = np.dot(first, second)
dot

32

In [24]:
# To apply the matrix multipication you can use the code below:
first_mat  = np.random.rand(3, 3)
second_mat = np.random.rand(3, 2)

prod = first_mat @ second_mat
prod

array([[0.39483381, 0.63998655],
       [0.3725455 , 0.57553967],
       [0.36207496, 0.62247679]])

In [25]:
array = np.array([1, 2, 3])

power = np.power(array, 2)
print(power)

[1 4 9]


## numpy broadcasting

In [26]:
array = np.array([1, 2, 3])
array = array + 2

array

array([3, 4, 5])

As you can see, we can add a scaler to an array. This behavior is commonly known as `numpy brodcasting` which means that the numpy copies the scaler to match the shape of the array, then sums it with the array.

## Slicing

In [27]:
matrix = np.random.rand(10, 10, 10)

print(matrix[0, 0, 0]) # The element at index 0, 0, 0
print(matrix[0, 0, 2:5]) # Elements which has the index 0,0,2 - 0,0,3, 0,0,4

0.8985990598796847
[0.31273921 0.12713944 0.06483988]


In [28]:
matrix = np.random.rand(2, 4, 5)

print(matrix[0, 0, :])

[0.62257769 0.61561168 0.83339707 0.62501058 0.92430376]


## Useful Methods

In [29]:
array = np.arange(0, 4, .2)
# This method works like python range method, but you can additionaly use floating points as the step
array

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8])

In [30]:
array = np.linspace(-10, 10, 20)
# You can use this method to linearly separate numbers (evenly spaced)
array

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [31]:
array = np.logspace(-10, 10, 20)
# You can use this method to logarithmically separate numbers
array

array([1.00000000e-10, 1.12883789e-09, 1.27427499e-08, 1.43844989e-07,
       1.62377674e-06, 1.83298071e-05, 2.06913808e-04, 2.33572147e-03,
       2.63665090e-02, 2.97635144e-01, 3.35981829e+00, 3.79269019e+01,
       4.28133240e+02, 4.83293024e+03, 5.45559478e+04, 6.15848211e+05,
       6.95192796e+06, 7.84759970e+07, 8.85866790e+08, 1.00000000e+10])

In [32]:
array = np.arange(12)
array = array.reshape(3, 4)
# You can use the reshape method to change the shape of an array

array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
array = np.arange(12)
array = array.reshape(3, -1)
# It is possible to use -1 for one of the indices

array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
array = np.random.rand(5, 2)
array = array.ravel()

# This method convets the array to a one-dimensional array

array

array([0.64193883, 0.80573642, 0.79966257, 0.41593616, 0.16810123,
       0.85513631, 0.84572669, 0.19026096, 0.96159275, 0.04240042])

In [35]:
array = np.random.rand(5, 2)
expanded_array = np.expand_dims(array, axis=0)

# This method adds a new dimention to the array

print(array.shape)
print(expanded_array.shape)

(5, 2)
(1, 5, 2)


In [36]:
array = np.random.rand(1, 5, 2, 1)
squeezed_array = np.squeeze(array)

# This method removes any dimension that has just one element.

print(array.shape)
print(squeezed_array.shape)

(1, 5, 2, 1)
(5, 2)


In [37]:
s = np.sum(array)
# This method sums up all the elements of the array
s

5.086479054176424

In [38]:
s = np.sum(array, axis=1)
# By specifying the axis parameter, numpy will sum through that axis
s

array([[[2.73701125],
        [2.34946781]]])

In [39]:
matrix = np.random.rand(4, 4)

mean = matrix.mean() # This method computed the mean of the array
std = matrix.std() # This method computed the standard-deviation of the array

first_axis_mean = matrix.mean(axis=0) # You can also specify the axis to calculate the mean of just that axis
first_axis_std = matrix.std(axis=0)# You can also specify the axis to calculate the standard-deviation of just that axis

print(f'total mean: {mean}')
print(f'toal std: {std}')
print()
print(f'first axis mean: {first_axis_mean}')
print(f'first axis std: {first_axis_std}')

total mean: 0.5122988355882323
toal std: 0.22946434414407624

first axis mean: [0.4550409  0.62831718 0.41736571 0.54847155]
first axis std: [0.19189288 0.10214905 0.19007558 0.31649648]


# Basic Linear Algebra

In [40]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.linalg.norm(matrix) # This method calculates the norm of a array

16.881943016134134

In [42]:
np.linalg.norm(matrix, 1) # It is also possible to specify the p parameter

18.0

In [43]:
np.linalg.det(matrix) # This method calculates the determinant of an array

-9.51619735392994e-16

In [44]:
np.linalg.inv(matrix) # This method calculates the inverse of an array

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [45]:
values, vectors = np.linalg.eig(matrix)

# This method calculates the eigenvalues and eigenvectors of a matrix

print(f'eigenvalues: {values}\n')
print(f'eigenvectos: {vectors}')

eigenvalues: [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]

eigenvectos: [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [46]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
u, s, v = np.linalg.svd(matrix)

# This method calulates the SVD (singular value decomposition) of a matrix

print(f'u: {u}\n')
print(f's: {s}\n')
print(f'v: {v}')

u: [[-0.3863177   0.92236578]
 [-0.92236578 -0.3863177 ]]

s: [9.508032   0.77286964]

v: [[-0.42866713 -0.56630692 -0.7039467 ]
 [-0.80596391 -0.11238241  0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]
